### PR TITLE
Added line breaks.

### PR DESCRIPTION
**Pull request by HenryBass**
Dividing line 17 into three lines can help with readability.

### CODE REVIEW

**Comment by CalvinMiller190** [comment]
makes sense, but why would it you need to change the changes? i just change it every time i make a new commit so it is correct

**Comment by HenryBass** [comment]
> makes sense, but why would it you need to change the changes? i just change it every time i make a new commit so it is correct

Sorry, this is my first time doing a pull request. I closed it bc it was making the program give an error. wdym by " why would it you need to change the changes".

**Comment by CalvinMiller190** [comment]
change the changes as in change the changes variable. it was set to 15500, because that was what it was when i had to make something new. but you changed it to 14000? just wondering why

**Comment by HenryBass** [comment]
sorry, didn't realise I changed it.

**Pull request closed without merging**
